//! # Trivela Campaign Contract
//!
//! On-chain campaign metadata and eligibility for Trivela.
//! Stores campaign config and allows checking participant status.
//!
//! Events:
//! - `register`: topics `(register, participant)`, data `()`
//! - `active`: topics `(active,)`, data `active: bool`
//! - `window`: topics `(window,)`, data `(start: u64, end: u64)`
//! - `maxcap`: topics `(maxcap,)`, data `max_cap: u64`
//! - `merkle`: topics `(merkle,)`, data `root: BytesN<32>`
//! - `pruned`: topics `(pruned, kind)`, data `count: u32`
//! - `invonly`: topics `(invonly,)`, data `enabled: bool`
//! - `invite`: topics `(invite,)`, data `invite_hash: BytesN<32>`
//! - `invrevk`: topics `(invrevk,)`, data `invite_hash: BytesN<32>`
//!
//! ## Storage pruning
//!
//! Participant records and multisig nonces are not bumped indefinitely on
//! Soroban; [`CampaignContract::prune_expired_participants`] and
//! [`CampaignContract::prune_used_nonces`] let anyone reclaim storage for
//! entries past their TTL, in capped batches. [`CampaignContract::storage_stats`]
//! reports current usage for monitoring.
//!
//! ## Invite-only registration
//!
//! When invite-only mode is enabled via `set_invite_only`, `register` requires
//! an `invite_code` whose `sha256` hash matches one issued via `issue_invite`
//! and not yet redeemed. Each invite hash is single-use.
//!
//! ## Co-admin multisig
//!
//! `set_merkle_root` is a critical operation: once a threshold is configured
//! via `set_multisig_threshold`, it requires at least that many valid
//! co-admin signatures (registered via `add_co_admin`) over
//! `(op, nonce, args_hash)`, verified with ed25519. The nonce is consumed on
//! use regardless of how many signers participated.
//!
//! ## Merkle allowlist
//!
//! When a Merkle root is set via `set_merkle_root`, all calls to `register`
//! must include both a `leaf` (the 32-byte value committed in the tree) and
//! a valid sibling-hash `proof`.
//!
//! ### Leaf convention
//! Off-chain tooling must build the tree with
//! `leaf = sha256(address_xdr_bytes)` for each allowlisted address, and pass
//! that pre-computed leaf on-chain.  Pairs are hashed in sorted order so
//! proofs are position-independent (the same convention as OpenZeppelin's
//! `MerkleProof`).
//!
//! ### Security note
//! `participant.require_auth()` ensures only the participant's own keypair
//! can submit a registration transaction, so a third party cannot register
//! an address on someone's behalf.  The expected leaf for a given address
//! should be generated by a trusted off-chain tool so that only genuinely
//! allowlisted addresses possess a valid `(leaf, proof)` pair.

#![no_std]

use soroban_sdk::{
    contract, contracterror, contractimpl, contractmeta, symbol_short, Address, Bytes, BytesN, Env,
    Symbol, Vec,
};

#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Error {
    Unauthorized = 100,
    OutsideTimeWindow = 101,
    CapReached = 102,
    CampaignInactive = 103,
    NotInAllowlist = 104,
    UnsupportedMigration = 105,
    InvalidAdminNonce = 106,
    InvalidWindow = 107,
    InviteCodeRequired = 108,
    InvalidInviteCode = 109,
    InviteAlreadyUsed = 110,
    InviteNotFound = 111,
    InvalidThreshold = 112,
    InsufficientSignatures = 113,
    NonceReused = 114,
    DuplicateSigner = 115,
    UnknownSigner = 116,
}

contractmeta!(key = "Description", val = "Trivela campaign configuration");

const ADMIN: Symbol = symbol_short!("admin");
const CAMPAIGN_ACTIVE: Symbol = symbol_short!("active");
const PARTICIPANT: Symbol = symbol_short!("partic");
const START_TIME: Symbol = symbol_short!("start");
const END_TIME: Symbol = symbol_short!("end");
const MAX_CAP: Symbol = symbol_short!("maxcap");
const PARTICIPANT_COUNT: Symbol = symbol_short!("count");
const MERKLE_ROOT: Symbol = symbol_short!("mkroot");
const SCHEMA_VERSION: Symbol = symbol_short!("schema_v");
const CURRENT_SCHEMA_VERSION: u32 = 1;
const ADMIN_NONCE: Symbol = symbol_short!("anonce");
const REGISTER_EVENT: Symbol = symbol_short!("register");
const SET_ACTIVE_EVENT: Symbol = symbol_short!("active");
const SET_WINDOW_EVENT: Symbol = symbol_short!("window");
const SET_MAX_CAP_EVENT: Symbol = symbol_short!("maxcap");
const SET_MERKLE_ROOT_EVENT: Symbol = symbol_short!("merkle");
const PRUNED_EVENT: Symbol = symbol_short!("pruned");

// ── pruning ──────────────────────────────────────────────────────────────────
const PARTICIPANT_REGISTRY: Symbol = symbol_short!("preg");
const PRUNE_CURSOR: Symbol = symbol_short!("pcursor");
/// Participant records older than this many ledgers are eligible for pruning.
const PARTICIPANT_TTL_LEDGERS: u32 = 1_036_800;
const NONCE_REGISTRY: Symbol = symbol_short!("nreg");
const NONCE_CURSOR: Symbol = symbol_short!("ncursor");
const NONCE_USED: Symbol = symbol_short!("msnonce");
/// Multisig nonces older than this many ledgers are eligible for pruning.
const NONCE_TTL_LEDGERS: u32 = 10_000;

// ── invite-only registration ────────────────────────────────────────────────
const INVITE_ONLY: Symbol = symbol_short!("invonly");
const INVITE_HASH: Symbol = symbol_short!("invhash");
const INVITE_USED: Symbol = symbol_short!("invused");
const SET_INVITE_ONLY_EVENT: Symbol = symbol_short!("invonly");
const ISSUE_INVITE_EVENT: Symbol = symbol_short!("invite");
const REVOKE_INVITE_EVENT: Symbol = symbol_short!("invrevk");

// ── co-admin multisig ────────────────────────────────────────────────────────
const CO_ADMINS: Symbol = symbol_short!("coadmin");
const MULTISIG_THRESHOLD: Symbol = symbol_short!("msthresh");
const OP_SET_MERKLE_ROOT: u32 = 1;

#[contract]
pub struct CampaignContract;

/// Hash two 32-byte values in sorted order so proofs are position-independent.
fn hash_pair(env: &Env, a: BytesN<32>, b: BytesN<32>) -> BytesN<32> {
    let (left, right) = if a <= b { (a, b) } else { (b, a) };
    let mut combined = [0u8; 64];
    combined[..32].copy_from_slice(&left.to_array());
    combined[32..].copy_from_slice(&right.to_array());
    env.crypto()
        .sha256(&Bytes::from_slice(env, &combined))
        .into()
}

/// Verify that `leaf` is included in the tree identified by `root` using the
/// given sibling-hash `proof`.
fn verify_merkle_proof(
    env: &Env,
    leaf: BytesN<32>,
    proof: &Vec<BytesN<32>>,
    root: &BytesN<32>,
) -> bool {
    let mut computed = leaf;
    for sibling in proof.iter() {
        computed = hash_pair(env, computed, sibling);
    }
    &computed == root
}

fn require_admin_with_nonce(env: &Env, admin: &Address, nonce: u64) -> Result<(), Error> {
    admin.require_auth();
    let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
    if &stored != admin {
        return Err(Error::Unauthorized);
    }
    let current: u64 = env.storage().instance().get(&ADMIN_NONCE).unwrap_or(0);
    if nonce != current {
        return Err(Error::InvalidAdminNonce);
    }
    env.storage().instance().set(&ADMIN_NONCE, &(current + 1));
    Ok(())
}

/// Build the signed payload for a multisig operation: `sha256(op || nonce || args_hash)`.
/// `op` is a stable per-function discriminant used in place of the function
/// name string (Symbol byte access is not available in `no_std`).
fn multisig_message(env: &Env, op: u32, nonce: u64, args_hash: &BytesN<32>) -> Bytes {
    let mut buf = [0u8; 44];
    buf[0..4].copy_from_slice(&op.to_be_bytes());
    buf[4..12].copy_from_slice(&nonce.to_be_bytes());
    buf[12..44].copy_from_slice(&args_hash.to_array());
    Bytes::from_slice(env, &buf)
}

/// Verify at least `required` distinct co-admin signatures over
/// `(op, nonce, args_hash)`, then consume `nonce` for replay protection.
/// The nonce is consumed regardless of how many signers submitted.
fn verify_multisig(
    env: &Env,
    op: u32,
    args_hash: BytesN<32>,
    nonce: u64,
    signatures: &Vec<(Address, BytesN<64>)>,
) -> Result<(), Error> {
    let required: u32 = env.storage().instance().get(&MULTISIG_THRESHOLD).unwrap_or(0);
    if required == 0 {
        return Ok(());
    }

    let nonce_key = (NONCE_USED, nonce);
    if env.storage().instance().get::<_, u32>(&nonce_key).is_some() {
        return Err(Error::NonceReused);
    }

    let co_admins: Vec<(Address, BytesN<32>)> =
        env.storage().instance().get(&CO_ADMINS).unwrap_or(Vec::new(env));
    let message = multisig_message(env, op, nonce, &args_hash);

    let mut seen: Vec<Address> = Vec::new(env);
    for (signer, sig) in signatures.iter() {
        if seen.iter().any(|s| s == signer) {
            return Err(Error::DuplicateSigner);
        }
        let pubkey = co_admins
            .iter()
            .find_map(|(addr, key)| if addr == signer { Some(key) } else { None })
            .ok_or(Error::UnknownSigner)?;
        env.crypto().ed25519_verify(&pubkey, &message, &sig);
        seen.push_back(signer.clone());
    }

    if seen.len() < required {
        return Err(Error::InsufficientSignatures);
    }

    env.storage().instance().set(&nonce_key, &env.ledger().sequence());
    let mut registry: Vec<u64> = env.storage().instance().get(&NONCE_REGISTRY).unwrap_or(Vec::new(env));
    registry.push_back(nonce);
    env.storage().instance().set(&NONCE_REGISTRY, &registry);
    Ok(())
}

#[contractimpl]
impl CampaignContract {
    /// Initialize campaign contract with an admin.
    pub fn initialize(env: Env, admin: Address) -> Result<(), Error> {
        env.storage().instance().set(&ADMIN, &admin);
        env.storage().instance().set(&CAMPAIGN_ACTIVE, &true);
        env.storage().instance().set(&START_TIME, &0u64);
        env.storage().instance().set(&END_TIME, &u64::MAX);
        env.storage().instance().set(&PARTICIPANT_COUNT, &0u64);
        env.storage()
            .instance()
            .set(&SCHEMA_VERSION, &CURRENT_SCHEMA_VERSION);
        env.storage().instance().set(&ADMIN_NONCE, &0u64);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Returns the active storage schema version for this contract.
    pub fn schema_version(env: Env) -> u32 {
        env.storage()
            .instance()
            .get(&SCHEMA_VERSION)
            .unwrap_or(CURRENT_SCHEMA_VERSION)
    }

    /// Migration entrypoint for future schema transitions.
    ///
    /// For now, version `1` is the only supported schema and this function
    /// serves as an idempotent migration hook for upgrade workflows.
    pub fn migrate(env: Env, admin: Address, target_version: u32) -> Result<u32, Error> {
        admin.require_auth();
        let stored: Address = env.storage().instance().get(&ADMIN).unwrap();
        if stored != admin {
            return Err(Error::Unauthorized);
        }
        if target_version != CURRENT_SCHEMA_VERSION {
            return Err(Error::UnsupportedMigration);
        }
        env.storage()
            .instance()
            .set(&SCHEMA_VERSION, &CURRENT_SCHEMA_VERSION);
        env.storage().instance().extend_ttl(50, 100);
        Ok(CURRENT_SCHEMA_VERSION)
    }

    /// Set registration time window (admin only).
    ///
    /// Both bounds are inclusive: `register` succeeds when
    /// `start <= now <= end`. Use `0` and `u64::MAX` for an effectively
    /// open window. Rejects `start > end` with `InvalidWindow`.
    pub fn set_window(
        env: Env,
        admin: Address,
        nonce: u64,
        start: u64,
        end: u64,
    ) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        if start > end {
            return Err(Error::InvalidWindow);
        }
        env.storage().instance().set(&START_TIME, &start);
        env.storage().instance().set(&END_TIME, &end);
        env.events().publish((SET_WINDOW_EVENT,), (start, end));
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Get the configured `(start, end)` registration window.
    ///
    /// Defaults to `(0, u64::MAX)` when no window has been set, which
    /// callers can interpret as "unbounded".
    pub fn get_window(env: Env) -> (u64, u64) {
        let start: u64 = env.storage().instance().get(&START_TIME).unwrap_or(0);
        let end: u64 = env.storage().instance().get(&END_TIME).unwrap_or(u64::MAX);
        (start, end)
    }

    /// Returns `true` when the current ledger timestamp is within
    /// `[start, end]` of the configured window.
    ///
    /// Off-chain callers and dependent contracts (e.g. rewards logic)
    /// can use this view to gate operations on campaign liveness without
    /// duplicating the window check.
    pub fn is_within_window(env: Env) -> bool {
        let now = env.ledger().timestamp();
        let start: u64 = env.storage().instance().get(&START_TIME).unwrap_or(0);
        let end: u64 = env.storage().instance().get(&END_TIME).unwrap_or(u64::MAX);
        now >= start && now <= end
    }

    /// Set campaign active flag (admin only).
    pub fn set_active(env: Env, admin: Address, nonce: u64, active: bool) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        env.storage().instance().set(&CAMPAIGN_ACTIVE, &active);
        env.events().publish((SET_ACTIVE_EVENT,), active);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Set maximum participant cap (admin only). Set to 0 for unlimited.
    pub fn set_max_cap(env: Env, admin: Address, nonce: u64, max_cap: u64) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        env.storage().instance().set(&MAX_CAP, &max_cap);
        env.events().publish((SET_MAX_CAP_EVENT,), max_cap);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Set the Merkle root for allowlist-gated registration.
    ///
    /// Once set, every `register` call must supply a valid `(leaf, proof)`.
    /// Remove the root by calling this again with a root of all zeros to
    /// revert to open registration.
    ///
    /// This is a critical operation: when a multisig threshold is configured
    /// (see [`Self::set_multisig_threshold`]), `signatures` must contain at
    /// least `required` valid co-admin signatures over
    /// `(op, nonce, sha256(root))`; otherwise pass an empty `Vec` and the
    /// legacy single-admin nonce check applies.
    pub fn set_merkle_root(
        env: Env,
        admin: Address,
        nonce: u64,
        root: BytesN<32>,
        signatures: Vec<(Address, BytesN<64>)>,
    ) -> Result<(), Error> {
        let threshold: u32 = env.storage().instance().get(&MULTISIG_THRESHOLD).unwrap_or(0);
        if threshold > 0 {
            let args_hash = env.crypto().sha256(&Bytes::from_slice(&env, &root.to_array())).into();
            verify_multisig(&env, OP_SET_MERKLE_ROOT, args_hash, nonce, &signatures)?;
        } else {
            require_admin_with_nonce(&env, &admin, nonce)?;
        }
        env.storage().instance().set(&MERKLE_ROOT, &root);
        env.events().publish((SET_MERKLE_ROOT_EVENT,), root.clone());
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Return the current Merkle root, or `None` when open registration is active.
    pub fn get_merkle_root(env: Env) -> Option<BytesN<32>> {
        env.storage().instance().get(&MERKLE_ROOT)
    }

    /// Register a participant.
    ///
    /// `leaf`  – the 32-byte leaf value committed in the Merkle tree for this
    ///           participant.  Must be `sha256(address_xdr_bytes)` for the
    ///           caller's address, computed by off-chain tooling.
    ///
    /// `proof` – ordered list of sibling hashes for the Merkle path from
    ///           `leaf` to the stored root.  Pass an empty `Vec` when no root
    ///           is configured.
    ///
    /// `invite_code` – required when invite-only mode is enabled (see
    ///           [`Self::set_invite_only`]); `sha256(invite_code)` must match
    ///           a hash issued via [`Self::issue_invite`] that has not yet
    ///           been redeemed. Pass `None` when invite-only mode is off.
    ///
    /// Returns `true` on first registration, `false` if already registered.
    pub fn register(
        env: Env,
        participant: Address,
        leaf: BytesN<32>,
        proof: Vec<BytesN<32>>,
        invite_code: Option<Bytes>,
    ) -> Result<bool, Error> {
        participant.require_auth();

        let active: bool = env
            .storage()
            .instance()
            .get(&CAMPAIGN_ACTIVE)
            .unwrap_or(false);
        if !active {
            return Err(Error::CampaignInactive);
        }

        let now = env.ledger().timestamp();
        let start: u64 = env.storage().instance().get(&START_TIME).unwrap_or(0);
        let end: u64 = env.storage().instance().get(&END_TIME).unwrap_or(u64::MAX);

        if now < start || now > end {
            return Err(Error::OutsideTimeWindow);
        }

        // Merkle allowlist check – skipped when no root is stored.
        if let Some(root) = env.storage().instance().get::<_, BytesN<32>>(&MERKLE_ROOT) {
            if !verify_merkle_proof(&env, leaf, &proof, &root) {
                return Err(Error::NotInAllowlist);
            }
        }

        let invite_only: bool = env.storage().instance().get(&INVITE_ONLY).unwrap_or(false);
        if invite_only {
            let code = invite_code.ok_or(Error::InviteCodeRequired)?;
            let invite_hash: BytesN<32> = env.crypto().sha256(&code).into();
            let hash_key = (INVITE_HASH, invite_hash.clone());
            if !env
                .storage()
                .instance()
                .get::<_, bool>(&hash_key)
                .unwrap_or(false)
            {
                return Err(Error::InvalidInviteCode);
            }
            let used_key = (INVITE_USED, invite_hash);
            if env.storage().instance().get::<_, bool>(&used_key).unwrap_or(false) {
                return Err(Error::InviteAlreadyUsed);
            }
            env.storage().instance().set(&used_key, &true);
        }

        let key = (PARTICIPANT, participant.clone());
        if env
            .storage()
            .instance()
            .get::<_, u32>(&key)
            .is_some()
        {
            return Ok(false);
        }

        let max_cap: u64 = env.storage().instance().get(&MAX_CAP).unwrap_or(0);
        if max_cap > 0 {
            let count: u64 = env
                .storage()
                .instance()
                .get(&PARTICIPANT_COUNT)
                .unwrap_or(0);
            if count >= max_cap {
                return Err(Error::CapReached);
            }
        }

        env.storage().instance().set(&key, &env.ledger().sequence());

        let mut registry: Vec<Address> = env
            .storage()
            .instance()
            .get(&PARTICIPANT_REGISTRY)
            .unwrap_or(Vec::new(&env));
        registry.push_back(participant.clone());
        env.storage().instance().set(&PARTICIPANT_REGISTRY, &registry);

        let count: u64 = env
            .storage()
            .instance()
            .get(&PARTICIPANT_COUNT)
            .unwrap_or(0);
        env.storage()
            .instance()
            .set(&PARTICIPANT_COUNT, &(count + 1));

        env.events().publish((REGISTER_EVENT, participant), ());

        env.storage().instance().extend_ttl(50, 100);
        Ok(true)
    }

    /// Deregister a participant.
    ///
    /// Checks liveness/window: if end_time is u64::MAX, checks if campaign is active;
    /// otherwise, checks if current timestamp <= end_time.
    pub fn deregister(env: Env, participant: Address) -> Result<bool, Error> {
        participant.require_auth();

        let end_time: u64 = env.storage().instance().get(&END_TIME).unwrap_or(u64::MAX);
        if end_time != u64::MAX {
            let now = env.ledger().timestamp();
            if now > end_time {
                return Err(Error::OutsideTimeWindow);
            }
        } else {
            let active: bool = env.storage().instance().get(&CAMPAIGN_ACTIVE).unwrap_or(false);
            if !active {
                return Err(Error::CampaignInactive);
            }
        }

        Ok(do_deregister(&env, participant))
    }

    /// Deregister a participant by the admin.
    ///
    /// Bypasses time window and liveness checks. Requires admin auth and nonce validation.
    pub fn admin_deregister(
        env: Env,
        admin: Address,
        nonce: u64,
        participant: Address,
    ) -> Result<bool, Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        Ok(do_deregister(&env, participant))
    }

    /// Check if a participant is registered.
    pub fn is_participant(env: Env, participant: Address) -> bool {
        env.storage()
            .instance()
            .get::<_, u32>(&(PARTICIPANT, participant))
            .is_some()
    }

    /// Check if campaign is active.
    pub fn is_active(env: Env) -> bool {
        env.storage()
            .instance()
            .get(&CAMPAIGN_ACTIVE)
            .unwrap_or(false)
    }

    /// Get current participant count.
    pub fn get_participant_count(env: Env) -> u64 {
        env.storage()
            .instance()
            .get(&PARTICIPANT_COUNT)
            .unwrap_or(0)
    }

    /// Get maximum participant cap (0 means unlimited).
    pub fn get_max_cap(env: Env) -> u64 {
        env.storage().instance().get(&MAX_CAP).unwrap_or(0)
    }

    /// Get the next required admin nonce for sensitive operations.
    pub fn admin_nonce(env: Env) -> u64 {
        env.storage().instance().get(&ADMIN_NONCE).unwrap_or(0)
    }

    // ── pruning (#451) ───────────────────────────────────────────────────

    /// Remove participant records whose TTL has passed, up to `max_entries`
    /// per call. Callable by anyone since it only deletes expired/stale
    /// data. Returns the number of entries pruned.
    pub fn prune_expired_participants(env: Env, max_entries: u32) -> u32 {
        let registry: Vec<Address> = env
            .storage()
            .instance()
            .get(&PARTICIPANT_REGISTRY)
            .unwrap_or(Vec::new(&env));
        let len = registry.len();
        if len == 0 || max_entries == 0 {
            return 0;
        }

        let now = env.ledger().sequence();
        let mut cursor: u32 = env.storage().instance().get(&PRUNE_CURSOR).unwrap_or(0);
        if cursor >= len {
            cursor = 0;
        }

        let mut pruned = 0u32;
        let mut checked = 0u32;
        let mut idx = cursor;
        while checked < len && pruned < max_entries {
            let addr = registry.get(idx).unwrap();
            let key = (PARTICIPANT, addr.clone());
            if let Some(registered_at) = env.storage().instance().get::<_, u32>(&key) {
                if now.saturating_sub(registered_at) > PARTICIPANT_TTL_LEDGERS {
                    env.storage().instance().remove(&key);
                    let count: u64 = env.storage().instance().get(&PARTICIPANT_COUNT).unwrap_or(0);
                    if count > 0 {
                        env.storage().instance().set(&PARTICIPANT_COUNT, &(count - 1));
                    }
                    pruned += 1;
                }
            }
            idx = (idx + 1) % len;
            checked += 1;
        }
        env.storage().instance().set(&PRUNE_CURSOR, &idx);

        if pruned > 0 {
            env.events().publish((PRUNED_EVENT, symbol_short!("partic")), pruned);
        }
        env.storage().instance().extend_ttl(50, 100);
        pruned
    }

    /// Remove multisig nonce records older than [`NONCE_TTL_LEDGERS`], up to
    /// `max_entries` per call. Callable by anyone since it only deletes
    /// stale data. Returns the number of entries pruned.
    pub fn prune_used_nonces(env: Env, max_entries: u32) -> u32 {
        let registry: Vec<u64> = env
            .storage()
            .instance()
            .get(&NONCE_REGISTRY)
            .unwrap_or(Vec::new(&env));
        let len = registry.len();
        if len == 0 || max_entries == 0 {
            return 0;
        }

        let now = env.ledger().sequence();
        let mut cursor: u32 = env.storage().instance().get(&NONCE_CURSOR).unwrap_or(0);
        if cursor >= len {
            cursor = 0;
        }

        let mut pruned = 0u32;
        let mut checked = 0u32;
        let mut idx = cursor;
        while checked < len && pruned < max_entries {
            let nonce = registry.get(idx).unwrap();
            let key = (NONCE_USED, nonce);
            if let Some(used_at) = env.storage().instance().get::<_, u32>(&key) {
                if now.saturating_sub(used_at) > NONCE_TTL_LEDGERS {
                    env.storage().instance().remove(&key);
                    pruned += 1;
                }
            }
            idx = (idx + 1) % len;
            checked += 1;
        }
        env.storage().instance().set(&NONCE_CURSOR, &idx);

        if pruned > 0 {
            env.events().publish((PRUNED_EVENT, symbol_short!("nonce")), pruned);
        }
        env.storage().instance().extend_ttl(50, 100);
        pruned
    }

    /// Storage stats for monitoring: `(participant_count, nonce_count, expired_estimate)`.
    /// `expired_estimate` counts currently-expired participant records.
    pub fn storage_stats(env: Env) -> (u64, u64, u64) {
        let participant_count: u64 = env.storage().instance().get(&PARTICIPANT_COUNT).unwrap_or(0);
        let nonce_registry: Vec<u64> = env
            .storage()
            .instance()
            .get(&NONCE_REGISTRY)
            .unwrap_or(Vec::new(&env));
        let nonce_count = nonce_registry.len() as u64;

        let now = env.ledger().sequence();
        let registry: Vec<Address> = env
            .storage()
            .instance()
            .get(&PARTICIPANT_REGISTRY)
            .unwrap_or(Vec::new(&env));
        let mut expired = 0u64;
        for addr in registry.iter() {
            if let Some(registered_at) = env.storage().instance().get::<_, u32>(&(PARTICIPANT, addr)) {
                if now.saturating_sub(registered_at) > PARTICIPANT_TTL_LEDGERS {
                    expired += 1;
                }
            }
        }
        (participant_count, nonce_count, expired)
    }

    // ── invite-only registration (#452) ─────────────────────────────────

    /// Toggle invite-only registration mode (admin only).
    pub fn set_invite_only(env: Env, admin: Address, nonce: u64, enabled: bool) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        env.storage().instance().set(&INVITE_ONLY, &enabled);
        env.events().publish((SET_INVITE_ONLY_EVENT,), enabled);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Issue an invite by storing its hash (admin only). The hash should be
    /// `sha256(invite_code)`, computed off-chain; the raw code is never
    /// stored on-chain.
    pub fn issue_invite(
        env: Env,
        admin: Address,
        nonce: u64,
        invite_hash: BytesN<32>,
    ) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        env.storage().instance().set(&(INVITE_HASH, invite_hash.clone()), &true);
        env.events().publish((ISSUE_INVITE_EVENT,), invite_hash);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Revoke a previously issued invite (admin only).
    pub fn revoke_invite(
        env: Env,
        admin: Address,
        nonce: u64,
        invite_hash: BytesN<32>,
    ) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        let key = (INVITE_HASH, invite_hash.clone());
        if !env.storage().instance().get::<_, bool>(&key).unwrap_or(false) {
            return Err(Error::InviteNotFound);
        }
        env.storage().instance().remove(&key);
        env.storage().instance().remove(&(INVITE_USED, invite_hash.clone()));
        env.events().publish((REVOKE_INVITE_EVENT,), invite_hash);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Returns whether invite-only registration mode is enabled.
    pub fn is_invite_only(env: Env) -> bool {
        env.storage().instance().get(&INVITE_ONLY).unwrap_or(false)
    }

    /// Returns whether the given invite hash has already been redeemed.
    pub fn invite_used(env: Env, invite_hash: BytesN<32>) -> bool {
        env.storage()
            .instance()
            .get(&(INVITE_USED, invite_hash))
            .unwrap_or(false)
    }

    // ── co-admin multisig (#454) ─────────────────────────────────────────

    /// Register a co-admin's ed25519 public key for multisig verification
    /// (admin only). Overwrites the key if `co_admin` is already registered.
    pub fn add_co_admin(
        env: Env,
        admin: Address,
        nonce: u64,
        co_admin: Address,
        pubkey: BytesN<32>,
    ) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        let mut co_admins: Vec<(Address, BytesN<32>)> =
            env.storage().instance().get(&CO_ADMINS).unwrap_or(Vec::new(&env));
        let mut found = false;
        for i in 0..co_admins.len() {
            let (addr, _) = co_admins.get(i).unwrap();
            if addr == co_admin {
                co_admins.set(i, (co_admin.clone(), pubkey.clone()));
                found = true;
                break;
            }
        }
        if !found {
            co_admins.push_back((co_admin, pubkey));
        }
        env.storage().instance().set(&CO_ADMINS, &co_admins);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Remove a co-admin from the multisig signer set (admin only).
    pub fn remove_co_admin(env: Env, admin: Address, nonce: u64, co_admin: Address) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        let co_admins: Vec<(Address, BytesN<32>)> =
            env.storage().instance().get(&CO_ADMINS).unwrap_or(Vec::new(&env));
        let mut remaining = Vec::new(&env);
        for (addr, pubkey) in co_admins.iter() {
            if addr != co_admin {
                remaining.push_back((addr, pubkey));
            }
        }
        env.storage().instance().set(&CO_ADMINS, &remaining);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Set the M-of-N multisig threshold for critical operations (admin only).
    /// `required = 0` disables multisig (legacy single-admin auth applies).
    pub fn set_multisig_threshold(env: Env, admin: Address, nonce: u64, required: u32) -> Result<(), Error> {
        require_admin_with_nonce(&env, &admin, nonce)?;
        let co_admins: Vec<(Address, BytesN<32>)> =
            env.storage().instance().get(&CO_ADMINS).unwrap_or(Vec::new(&env));
        if required > co_admins.len() {
            return Err(Error::InvalidThreshold);
        }
        env.storage().instance().set(&MULTISIG_THRESHOLD, &required);
        env.storage().instance().extend_ttl(50, 100);
        Ok(())
    }

    /// Returns the configured M-of-N multisig threshold (0 = disabled).
    pub fn multisig_threshold(env: Env) -> u32 {
        env.storage().instance().get(&MULTISIG_THRESHOLD).unwrap_or(0)
    }
}

fn do_deregister(env: &Env, participant: Address) -> bool {
    let key = (PARTICIPANT, participant.clone());
    if env.storage().instance().get::<_, u32>(&key).is_none() {
        return false;
    }
    env.storage().instance().remove(&key);
    let count: u64 = env.storage().instance().get(&PARTICIPANT_COUNT).unwrap_or(0);
    if count > 0 {
        env.storage().instance().set(&PARTICIPANT_COUNT, &(count - 1));
    }
    env.events().publish(
        (Symbol::new(env, "deregister"), participant),
        (),
    );
    env.storage().instance().extend_ttl(50, 100);
    true
}

#[cfg(test)]
mod test;

